### ISSUE TITLE
Dot and comma Problem

### ISSUE THREAD

**Issue by MicKBfr** [jorgedlcruz/veeam-enterprise_manager-grafana#1]
Hi Jorge,

This script is really good

I have use your script and i have been a problem with comma
"REPO - Default Backup Repository" : 28,68 ,

i had the fallowing 
$Free = $FreeP -replace ',','.'

And the script to became successful

Do you think, it's possible to have more detail from Rest Api?

Thanks

**Comment by jorgedlcruz** [comment]
Hi Mick,
Thank you for the comment, I've pushed a new version. The Veeam RESTfulAPI it's so dense and complete, we will need to see what else we want to monitor, some examples here:
https://helpcenter.veeam.com/docs/backup/rest/reports_summary_overview.html?ver=95
https://helpcenter.veeam.com/docs/backup/rest/reports_summary_vms_overview.html?ver=95
https://helpcenter.veeam.com/docs/backup/rest/reports_summary_statistics.html?ver=95
etc
Ideas :)?

**Comment by MicKBfr** [comment]
Hi Jose,

Thanks  for your reply

Perhaps we can make a chronogram
A separation between jobs:
backup jobs
backups copy jobs
Replication jobs
Sure backup jobs
..
To have more precision  

I have try yesterday on our lab 
![image](https://user-images.githubusercontent.com/29974236/28710273-b1e50150-7383-11e7-9841-4cfb393e00d6.png)

My development skills are limited :-(

**Comment by jorgedlcruz** [comment]
Hi Mick, 
Let me try and add more stuff during the weekend. Thank you fro trying it.
