### ISSUE TITLE
Code invalid error

### ISSUE THREAD

**Issue by andrewm659** [jorgedlcruz/veeam-enterprise_manager-grafana#12]
Not sure what this means but I getting the following:

HTTP/1.1 400 Bad Request
Content-Type: application/json; charset=utf-8
X-Influxdb-Build: OSS
X-Influxdb-Version: v2.2.0
X-Platform-Error-Code: invalid
Date: Thu, 21 Apr 2022 16:59:05 GMT
Content-Length: 459

{"code":"invalid","message":"unable to parse 'veeam_em_overview_jobs,host=https://backup.fqdn.com,veeamMaxDurationBackupJobName=None,veeamMaxDurationReplicaJobName=None veeamRunningJobs=,veeamScheduledJobs=,veeamScheduledBackupJobs=,veeamScheduledReplicaJobs=,veeamTotalJobRuns=,veeamSuccessfulJobRuns=,veeamWarningsJobRuns=,veeamFailedJobRuns=,veeamMaxJobDuration=,veeamMaxBackupJobDuration=,veeamMaxReplicaJobDuration=': missing field value"}[

**Comment by jorgedlcruz** [comment]
Hello,
What version of Enterprise manager are you using, and also, what license do you have, Enterprise, Enterprise Plus, VUL?
Also on the login, how does the username look like user@domain.tld or domain\user?

**Comment by andrewm659** [comment]
So I'm running the latest version of bash script. We have the Enterprise Plus license.  The login is formatted like an email address.  I think I got this working.  It was an AD access issue.

**Comment by orrionis** [comment]
Hi i have the same issue, but before i have lot of fault:

```
./veeam_enterprisemanager.sh: ligne 37: jq : commande introuvable
./veeam_enterprisemanager.sh: ligne 48: jq : commande introuvable
./veeam_enterprisemanager.sh: ligne 49: jq : commande introuvable
./veeam_enterprisemanager.sh: ligne 50: jq : commande introuvable
./veeam_enterprisemanager.sh: ligne 51: jq : commande introuvable
./veeam_enterprisemanager.sh: ligne 52: jq : commande introuvable
./veeam_enterprisemanager.sh: ligne 53: jq : commande introuvable
./veeam_enterprisemanager.sh: ligne 54: jq : commande introuvable
./veeam_enterprisemanager.sh: ligne 55: jq : commande introuvable
Writing veeam_em_overview to InfluxDB
HTTP/1.1 400 Bad Request
Content-Type: application/json
Request-Id: e5388815-cbb7-11ec-8320-0050563c855d
X-Influxdb-Build: OSS
X-Influxdb-Error: unable to parse 'veeam_em_overview,host=192.168.3.15 veeamBackupServers=,veeamProxyServers=,veeamRepositoryServers=,veeamRunningJobs=,veeamScheduledJobs=,veeamSuccessfulVmLastestStates=,veeamWarningVmLastestStates=,veeamFailedVmLastestStates=': missing field value
X-Influxdb-Version: 1.8.10
X-Request-Id: e5388815-cbb7-11ec-8320-0050563c855d
Date: Wed, 04 May 2022 14:38:42 GMT
Content-Length: 277
```
have any idea;

**Comment by jorgedlcruz** [comment]
Hello,
Have you installed jq? sudo apt-get install jq

Try it and let me know

**Comment by orrionis** [comment]
of course, basic error sorry

**Comment by orrionis** [comment]
last question, it's normal that :

`jq: error (at <stdin>:1): Cannot iterate over null (null)`

**Comment by jorgedlcruz** [comment]
It depends; what section are you in? Should say some lines before, imagine, you might be on the NAS Backup Loops, and you do not have NAS Jobs.

I need to work a bit on the error handling :)

**Comment by orrionis** [comment]
ok i d'ont no it'st the result of script , 


```
root@srv:~# ./veeam_enterprisemanager.sh
Writing veeam_em_overview to InfluxDB
HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: 6a1e7cc4-cc74-11ec-bf26-0050563c855d
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.8.10
X-Request-Id: 6a1e7cc4-cc74-11ec-bf26-0050563c855d
Date: Thu, 05 May 2022 13:08:11 GMT

Writing veeam_em_overview_vms to InfluxDB
HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: 6a54bb60-cc74-11ec-bf27-0050563c855d
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.8.10
X-Request-Id: 6a54bb60-cc74-11ec-bf27-0050563c855d
Date: Thu, 05 May 2022 13:08:11 GMT

Writing veeam_em_overview_jobs to InfluxDB
HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: 6a9c759f-cc74-11ec-bf2a-0050563c855d
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.8.10
X-Request-Id: 6a9c759f-cc74-11ec-bf2a-0050563c855d
Date: Thu, 05 May 2022 13:08:11 GMT

Writing veeam_em_overview_repositories to InfluxDB
HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: 6ac5c5a8-cc74-11ec-bf2b-0050563c855d
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.8.10
X-Request-Id: 6ac5c5a8-cc74-11ec-bf2b-0050563c855d
Date: Thu, 05 May 2022 13:08:12 GMT

Writing veeam_em_overview_repositories to InfluxDB
HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: 6ae74623-cc74-11ec-bf2c-0050563c855d
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.8.10
X-Request-Id: 6ae74623-cc74-11ec-bf2c-0050563c855d
Date: Thu, 05 May 2022 13:08:12 GMT


Writing veeam_em_backup_servers to InfluxDB
HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: 6b0af6f1-cc74-11ec-bf2d-0050563c855d
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.8.10
X-Request-Id: 6b0af6f1-cc74-11ec-bf2d-0050563c855d
Date: Thu, 05 May 2022 13:08:12 GMT

jq: error (at <stdin>:1): Cannot iterate over null (null)
jq: error (at <stdin>:1): Cannot iterate over null (null)
jq: error (at <stdin>:1): Cannot iterate over null (null)
jq: error (at <stdin>:1): Cannot iterate over null (null)
jq: error (at <stdin>:1): Cannot iterate over null (null)
jq: error (at <stdin>:1): Cannot iterate over null (null)
jq: error (at <stdin>:1): Cannot iterate over null (null)
```

**Comment by orrionis** [comment]
and in my grafana works at half
![Capture d’écran 2022-05-05 151407](https://user-images.githubusercontent.com/65168007/166930727-03de2713-827c-4e10-9fc8-bc60c5571e95.png)

**Comment by jorgedlcruz** [comment]
Looks good until it needs to jump into the Job Sessions. The script will by default try to pull the sessions for the last 24 hours, it is a variable at the top that you can edit if you like:
`timestart=$(date --date="-1 days" +%FT%TZ)`

Do you have Job sessions over the last 24 hours at all? Maybe edit that variable and put -7 days and see

**Comment by jorgedlcruz** [comment]
Oh, wait a minute, 9.5 Update 4. I think it is deprecated by now, since January 2022, and you should be thinking to upgrade to v10, or v11 - https://www.veeam.com/product-lifecycle.html?ad=in-text-link

Perhaps some API calls were different back then. I remember not having any issue on v10, or v11. Try to expand the range, but as said, some APIs might be different.

**Comment by orrionis** [comment]
ok i try this

the veeam backup work fine since 2 month

**Comment by orrionis** [comment]
Hi, 
i upgrade VBR, to 11. and.... no change, 
 first i have nodata for veeam backup performace, perhaps, telegraf work fine

![Capture d’écran 2022-05-06 091010](https://user-images.githubusercontent.com/65168007/167084165-8948aff8-8d8a-450c-b10a-eb71af2f3b19.png)
![Capture d’écran 2022-05-06 090924](https://user-images.githubusercontent.com/65168007/167084168-5f54b494-77b7-4fc7-afe5-baedac02531b.png)


My telegraf conf:

```
[[inputs.win_perf_counters]]
  [[inputs.win_perf_counters.object]]
    # Processor usage, alternative to native, reports on a per core.
    ObjectName = "Processor"
    Instances = ["*"]
    Counters = [
      "% Idle Time",
      "% Interrupt Time",
      "% Privileged Time",
      "% User Time",
      "% Processor Time"
    ]
    Measurement = "win_cpu"
    # Set to true to include _Total instance when querying for all (*).
    #IncludeTotal=false

  [[inputs.win_perf_counters.object]]
    # Disk times and queues
    ObjectName = "LogicalDisk"
    Instances = ["*"]
    Counters = [
      "% Idle Time",
      "% Disk Time",
      "% Disk Read Time",
      "% Disk Write Time",
      "% User Time",
      "% Free Space",
      "Current Disk Queue Length",
      "Free Megabytes",
      "Disk Read Bytes/sec",
      "Disk Write Bytes/sec"
    ]
    Measurement = "win_disk"
    # Set to true to include _Total instance when querying for all (*).
    #IncludeTotal=false

  [[inputs.win_perf_counters.object]]
    ObjectName = "System"
    Counters = [
      "Context Switches/sec",
      "System Calls/sec",
      "Processor Queue Length",
      "Threads",
      "System Up Time",
      "Processes"
    ]
    Instances = ["------"]
    Measurement = "win_system"
    # Set to true to include _Total instance when querying for all (*).
    #IncludeTotal=false

  [[inputs.win_perf_counters.object]]
    # Example query where the Instance portion must be removed to get data back,
    # such as from the Memory object.
    ObjectName = "Memory"
    Counters = [
      "Available Bytes",
      "Cache Faults/sec",
      "Demand Zero Faults/sec",
      "Page Faults/sec",
      "Pages/sec",
      "Transition Faults/sec",
      "Pool Nonpaged Bytes",
      "Pool Paged Bytes"
    ]
    # Use 6 x - to remove the Instance bit from the query.
    Instances = ["------"]
    Measurement = "win_mem"
    # Set to true to include _Total instance when querying for all (*).
    #IncludeTotal=false

  [[inputs.win_perf_counters.object]]
    # more counters for the Network Interface Object can be found at
    # https://msdn.microsoft.com/en-us/library/ms803962.aspx
    ObjectName = "Network Interface"
    Counters = [
      "Bytes Received/sec",
      "Bytes Sent/sec",
      "Packets Received/sec",
      "Packets Sent/sec"
    ]
    Instances = ["*"] # Use 6 x - to remove the Instance bit from the query.
    Measurement = "win_net"
    #IncludeTotal=false #Set to true to include _Total instance when querying for all (*).

  [[inputs.win_perf_counters.object]]
    # Process metrics
    ObjectName = "Process"
    Counters = [
      "% Processor Time",
      "Handle Count",
      "Private Bytes",
      "Thread Count",
      "Virtual Bytes",
      "Working Set"
      ]
    Instances = ["*"]
    Measurement = "win_proc"
    #IncludeTotal=false #Set to true to include _Total instance when querying for all (*).
```

What its wrong ??

**Comment by jorgedlcruz** [comment]
Hello,
Step by step. Has the backup sessions been fixed? No more errors on the
script?

**Comment by orrionis** [comment]
![Capture d’écran 2022-05-06 093109](https://user-images.githubusercontent.com/65168007/167087348-5d0785ff-9cd4-4a2f-872f-1c7d89de9b7a.png)


I have always the error 
jq: error (at <stdin>:1): Cannot iterate over null (null)
jq: error (at <stdin>:1): Cannot iterate over null (null)
jq: error (at <stdin>:1): Cannot iterate over null (null)
jq: error (at <stdin>:1): Cannot iterate over null (null)
jq: error (at <stdin>:1): Cannot iterate over null (null)
jq: error (at <stdin>:1): Cannot iterate over null (null)
jq: error (at <stdin>:1): Cannot iterate over null (null)

**Comment by orrionis** [comment]
Ok i see why 

in tab 
veeam backup Server there a nothing

![Capture d’écran 2022-05-06 100328](https://user-images.githubusercontent.com/65168007/167092170-d39e90f2-2268-4aa3-982d-6a81b8b0d398.png)

**Comment by orrionis** [comment]
and the query based on $veeamserver$ 

but why there nothing 

in Entreprise manager i have the name of my server

**Comment by jorgedlcruz** [comment]
Hello,
Would you mind confirming the InfluxDB Version? How does it look your telegraf output for the Influx part, remove your password ofc, and if you have edited this on your telegraf.conf please 

`hostname = "yourvbr.yourdomain.com"`

**Comment by orrionis** [comment]
```
# Telegraf Configuration
# Configuration for telegraf agent
[agent]
  interval = "30s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""
  hostname = "FOUG-HV"
  omit_hostname = false
```

**Comment by orrionis** [comment]
> 

influx 1.8

**Comment by orrionis** [comment]
oh danmed, i run a standard license it maybe the problem

![Capture d’écran 2022-05-06 104757](https://user-images.githubusercontent.com/65168007/167099046-e24d41ea-1c74-4dd1-9d89-177be9a6a7d2.png)

**Comment by jorgedlcruz** [comment]
Alright,
So, you are using all the scripts and grafana dashboard from here, right?
https://github.com/jorgedlcruz/veeam-enterprise_manager-grafana/tree/master/InfluxDB%20v1.8

The Veeam Server I always take it from the sessions call, which is unfortunate as in your case it is failing, I am not sure why just yet.

Yep, most likely that is the issue, as Standard can grab some info from the API, but not all.

**Comment by jorgedlcruz** [comment]
I am going to close the issue now, let me know if you need more help :)
