### ISSUE TITLE
no CPU / RAM / Network usage

### ISSUE THREAD

**Issue by eglyn** [jorgedlcruz/veeam-enterprise_manager-grafana#8]
hi !
Your script works great with veeam information, but server informations (ram, cpu, network) stay greyed :/

I use veeam entreprise 11, do I need to do something to have this stats ? 

![image](https://user-images.githubusercontent.com/24936778/119091180-f6ec7e80-ba0c-11eb-897d-5e99ea127492.png)

thx !

**Comment by jorgedlcruz** [comment]
Hello,
Thanks so much, to achieve that, you need to install the telegraf agent on
the server, full procedure can be found on the blog
https://jorgedelacruz.uk/2020/01/07/looking-for-the-perfect-dashboard-influxdb-telegraf-and-grafana-part-xix-monitoring-veeam-with-enterprise-manager-shell-script/

Thanks, let me know :)

**Comment by eglyn** [comment]
thx ! it works !, I missed this step :)
