### ISSUE TITLE
Error when executing the script

### ISSUE THREAD

**Issue by concept-trainer** [jorgedlcruz/veeam-enterprise_manager-grafana#9]
I have Grafana 7.2 with Telegraf and InfluxDB 1.8 and i have so many dashboards with telegraf which are working fine except this one.

i am getting the error as below. please guide why i am getting this error.

./veeam_enterprisemanager.sh: line 37: jq: command not found
./veeam_enterprisemanager.sh: line 48: jq: command not found
./veeam_enterprisemanager.sh: line 49: jq: command not found
./veeam_enterprisemanager.sh: line 50: jq: command not found
./veeam_enterprisemanager.sh: line 51: jq: command not found
./veeam_enterprisemanager.sh: line 52: jq: command not found
./veeam_enterprisemanager.sh: line 53: jq: command not found
./veeam_enterprisemanager.sh: line 54: jq: command not found
./veeam_enterprisemanager.sh: line 55: jq: command not found
Writing veeam_em_overview to InfluxDB
HTTP/1.1 400 Bad Request
Content-Type: application/json
Request-Id: 924c5e03-0fc7-11ec-a0a8-005056ba9919
X-Influxdb-Build: OSS
X-Influxdb-Error: unable to parse 'veeam_em_overview,host=192.168.1.1 veeamBackupServers=,veeamProxyServers=,veeamRepositoryServers=,veeamRunningJobs=,veeamScheduledJobs=,veeamSuccessfulVmLastestStates=,veeamWarningVmLastestStates=,veeamFailedVmLastestStates=': missing field value
X-Influxdb-Version: 1.8.4
X-Request-Id: 924c5e03-0fc7-11ec-a0a8-005056ba9919
Date: Tue, 07 Sep 2021 10:37:16 GMT
Content-Length: 277

**Comment by jorgedlcruz** [comment]
Hello,
Thank you for the comment, you will need to download jq for my bash shell. So apt-get install jq, or yum install jq, and run the script again.

Best regards

**Comment by concept-trainer** [comment]
Hi   Jorgedlcruz

After following your instructions my issue has been resolved.  Thanks for your kind reply.

Writing veeam_em_job_sessions to InfluxDB
HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: 921e67ed-0fd7-11ec-a9c3-005056ba9919
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.8.4
X-Request-Id: 921e67ed-0fd7-11ec-a9c3-005056ba9919
Date: Tue, 07 Sep 2021 12:31:48 GMT

Regards,
Noor Uz Zaman
Concept Trainer.

**Comment by jorgedlcruz** [comment]
Glad to hear, have a great day
